apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  nodeSelector:
    # TODO: minikube multi node로 실행해야함
    # kubernetes.io/hostname: k8s-node1
    kubernetes.io/hostname: minikube
  containers:
    - name: container
      image: tmkube/init
