apiVersion: v1
kind: Pod
metadata:
  name: pod-4
spec:
  containers:
    - name: container
      image: tmkube/init
      resources:
        requests:
          memory: 512Mi
        limits:
          memory: 1.5Gi
