# apiVersion: v1
# kind: LimitRange
# metadata:
#   name: lr-1
#   namespace: nm-5
# spec:
#   limits:
#     - type: Container
#       min:
#         memory: 0.1Gi
#       max:
#         memory: 0.4Gi
#       maxLimitRequestRatio:
#         memory: '3'
#       defaultRequest:
#         memory: 0.1Gi
#       default:
#         memory: 0.2Gi

apiVersion: v1
kind: LimitRange
metadata:
  name: lr-5
  namespace: nm-6
spec:
  limits:
    - type: Container
      min:
        memory: 0.1Gi
      max:
        memory: 0.5Gi
      maxLimitRequestRatio:
        memory: '1'
      defaultRequest:
        memory: 0.5Gi
      default:
        memory: 0.5Gi

---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-3
  namespace: nm-6
spec:
  limits:
    - type: Container
      min:
        memory: 0.1Gi
      max:
        memory: 0.3Gi
      maxLimitRequestRatio:
        memory: '1'
      defaultRequest:
        memory: 0.3Gi
      default:
        memory: 0.3Gi
