apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
    - name: container
      image: tmkube/app
      resources:
        requests:
          memory: 0.5Gi
        limits:
          memory: 0.5Gi
