apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: pod
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube-m02
  containers:
    - name: container
      image: tmkube/app
      ports:
        - containerPort: 8080
