apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-03
spec:
  capacity:
    # storage: 1G
    storage: 2G
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
  local:
    path: /node-v
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: [minikube]
